### ISSUE TITLE
Unknown txQueue error

### ISSUE THREAD

**Issue by snowkidind** [snowkidind/txTheRipper#5]
2024-07-11 03:35:42 New Block:20278525 behind by: 132891 blocks
RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at commitMem (/txRipper/application/extractBatch.js:48:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async extractBatch (/txRipper/application/extractBatch.js:112:22)
    at async Object.synchronize (/txRipper/application/sync.js:87:27)
    at async doSynchronize (/txRipper/ripper.js:217:22)
    at async WebSocketProvider.<anonymous> (/txRipper/ripper.js:239:5)
2024-07-11 03:35:56 Application Error in extractBatch

**Comment by snowkidind** [comment]
This appears to be because of a transaction batch exceeding the maximum JSON size and crashing on JSON.stringify

I was able to reduce JSON_TX_FILE_MAX to 50000000 in order to get the offending segment to pass. 

JSON_TX_FILE_MAX is a index that is used as a guide as to when there is enough data in the queue to warrant a database commit. It represents the knee between "excessive" disc writes and memory usage. The culprit of this being triggered is probably a massive airdrop which appears near the end of a batch, exceeding the limit by far.

**Comment by snowkidind** [comment]
Apparently there is some sort of echoing in the application since an update of some sort, will require deep dive

**Comment by snowkidind** [comment]
This was found to be a hardware latency issue where the nodes websocket provider sent many blocks instantaneously and it outran the db insert which locks the status. I installed a de-bouncer to prevent this from occurring.

**Comment by snowkidind** [comment]
This was found to be a hardware latency issue where the nodes websocket provider sent many blocks instantaneously and it outran the db insert which locks the status. I installed a de-bouncer to prevent this from occurring.
